### ISSUE TITLE
Unique measure to groupby aggregation

### ISSUE THREAD

**Issue by arvind** [uwdata/datalib#18]
We have `dl.unique`. If we were able to add a `unique` measure to the groupby aggregation, we could get rid of the top-level "Unique" transform in Vega.

**Comment by jheer** [comment]
In Vega 1, unique simply returns a flat array of unique values. This result
is analogously expressible using `dl.groupby('field').count()`, which will
return an array of tuples containing the unique values of 'field' and their
associated counts.

Are you requesting a different facility, such as a collection unique values
per group? (e.g., `dl.groupby('field1').summarize({'field2':'unique'})`) If
so, what should the semantics be? Do you want an array of unique values
only? An array of unique values plus counts (as in the first example above)?

**Comment by arvind** [comment]
You're right, counting + groupby is sufficient to replicate the original transform.
