### ISSUE TITLE
Bivariate Stats

### ISSUE THREAD

**Issue by kanitw** [uwdata/datalib#2]
- [x]  mutual information 
- [x] correlation.

**Comment by jheer** [comment]
I considered adding these, but there are some issues to iron out.

- For correlation, should the input be two flat arrays of numerical values? Or a table and two fields to test for correlation? Or two tables (which may or may not be the same) and two fields?
- Mutual information requires bins. The input could be a table of bin values with duplicates (2d table) or a table of 2D bin labels plus counts (3d table). Also, right now datalib includes facilities for generating bin specifications, but not for computing the actual bin assignments for input data. We need to decide what aspects datalib should be responsible for here.

What makes the most sense given your downstream use cases?

**Comment by jheer** [comment]
I've added dot product and correlation methods, which accept either two vectors or a single table and two accessors as input. We still need to decide to what degree we wish to handle binning and mutual information.

**Comment by kanitw** [comment]
That's a good point.   @domoritz – I guess you're also interested in this.  

As you described earlier that this should be library that people use to wrangle and profile data in node console, I think datalib should support binning and value derivation too?  

I think a naive application of this in voyager for a table with d variables is to calculate ~d^2 mutual information value (for every pair).  

With this use case, we can decouple the process into 3 methods:

(1) input raw table -> output binned table + a set of histograms `Hx` for each variable `x`.

For quantitative variables, we simply bin them (with some default max bin size?)
For categorical variable, each unique value could serve as the bin itself for lower cardinality case. 
However, for higher cardinality, we also need to bin the data with some kind of hash function?

(2) input a (binned) table and two accessors for `x,y` -> output a 2d histogram table `Hxy` that contains tuples of `(x,y,count)`.

(3) input `Hxy`,`Hx` and `Hy` -> output mutual information.

**Comment by jheer** [comment]
Added mutual information (dl.entropy.mutual) which accepts either three arrays (x, y, count) as input or a table and three accessors.
