### ISSUE TITLE
agg._mod with accessors incorrectly calculates min/max

### ISSUE THREAD

**Issue by arvind** [uwdata/datalib#22]
```js
var dl = require('./src/index')
var agg = dl.groupby().stream(true).key("_id").summarize({'vg_dataref': ['min', 'max'] });

var add1 = [
  { x: 1, y: 28, _id: 1 },
  { x: 2, y: 55, _id: 2 },
  { x: 3, y: 43, _id: 3 },
  { x: 4, y: 91, _id: 4 },
  { x: 5, y: 81, _id: 5 },
  { x: 6, y: 53, _id: 6 },
  { x: 7, y: 19, _id: 7 },
  { x: 8, y: 87, _id: 8 },
  { x: 9, y: 52, _id: 9 },
  { x: 10, y: 48, _id: 10 }
];

var add2 = [
  { a: 11, b: 24, _id: 11 },
  { a: 12, b: 49, _id: 12 },
  { a: 13, b: 87, _id: 13 },
  { a: 14, b: 66, _id: 14 },
  { a: 15, b: 17, _id: 15 },
  { a: 16, b: 27, _id: 16 },
  { a: 17, b: 68, _id: 17 },
  { a: 18, b: 16, _id: 18 },
  { a: 19, b: 49, _id: 19 },
  { a: 20, b: 15, _id: 20 }
];

var mod1 = [
  { x: 1, y: 56, _id: 1 },
  { x: 2, y: 110, _id: 2 },
  { x: 3, y: 86, _id: 3 },
  { x: 4, y: 182, _id: 4 },
  { x: 5, y: 162, _id: 5 },
  { x: 6, y: 106, _id: 6 },
  { x: 7, y: 38, _id: 7 },
  { x: 8, y: 174, _id: 8 },
  { x: 9, y: 104, _id: 9 },
  { x: 10, y: 96, _id: 10 }
];

var mod2 = [
  { a: 11, b: 48, _id: 11 },
  { a: 12, b: 98, _id: 12 },
  { a: 13, b: 174, _id: 13 },
  { a: 14, b: 132, _id: 14 },
  { a: 15, b: 34, _id: 15 },
  { a: 16, b: 54, _id: 16 },
  { a: 17, b: 136, _id: 17 },
  { a: 18, b: 32, _id: 18 },
  { a: 19, b: 98, _id: 19 },
  { a: 20, b: 30, _id: 20 }
];

function mod(acc, mod, add) {
  agg.accessors({ 'vg_dataref': acc });

  for(var i=0; i<mod.length; ++i) {
    var t = mod[i],
        a = add[i],
        p;

    if(acc == 'y') {
      p = {x: a.x, y: a.y, _id: a.id};
      a.x = t.x; a.y = t.y;
    } else {
      p = {a: a.a, b: a.b, _id: a.id};
      a.a = t.a; a.b = t.b;
    }

    agg._mod(a, p);
  }
}
```

This produces the correct result:
```js
agg.accessors({ 'vg_dataref': 'y' });
add1.forEach(function(x) { agg._add(x); });

console.log(agg.result()); // [ { min_vg_dataref: 19, max_vg_dataref: 91 } ]

mod('y', mod1, add1);

console.log(agg.result()); // [ { min_vg_dataref: 38, max_vg_dataref: 182 } ]
```

As does this:
```js
agg.accessors({ 'vg_dataref': 'b' });
add2.forEach(function(x) { agg._add(x); });

console.log(agg.result()); // [ { min_vg_dataref: 15, max_vg_dataref: 87 } ]

mod('b', mod2, add2)

console.log(agg.result()); // [ { min_vg_dataref: 30, max_vg_dataref: 174 } ]
```

But this produces an incorrect result:
```js
agg.accessors({ 'vg_dataref': 'y' });
add1.forEach(function(x) { agg._add(x); });

agg.accessors({ 'vg_dataref': 'b' });
add2.forEach(function(x) { agg._add(x); });

console.log(agg.result()); // Correct: [ { min_vg_dataref: 15, max_vg_dataref: 91 } ]

mod('y', mod1, add1);
mod('b', mod2, add2)

console.log(agg.result()); // Incorrect: [ { min_vg_dataref: 30, max_vg_dataref: 174 } ]. Expected max to be 182.
```

**Comment by jheer** [comment]
This example points to a simpler, but more profound error in the aggregator: now that we collect tuples instead of values (for median, streaming min/max, etc) we can not accurately compute statistics from the tuples in the collector if the accessor has been changed.

When we collected values directly (on a per aggr-cell basis) this was not a problem, as the accessor was called once then forgotten. When we need to call the accessor on every collected tuple, we have problems. This is a systemic issue that requires change to the architecture or API.

I propose we change the API and remove the ability of an aggregator to change its accessor. This is a minimal change to the datalib code base and preserves the other nice features we have. In response, we will need to (a) craft a multi-aggregator strategy for driving scales domains in Vega or (b) simply pre-apply an accessor prior to aggregation, thus resulting in a single schema for the aggregator.

For example, with some straightforward modifications to the collector, the following is possible:
```javascript
var agg = dl.groupby().stream(true).summarize([{
  name: 'value',
  get:  dl.identity,
  ops:  ['min', 'max'],
  as:   ['min', 'max']
}]);

var domain1 = [{a:1}, {a:3}, {a:6}];
var domain2 = [{b:10}, {b:2}];
var f1 = dl.$('a');
var f2 = dl.$('b');

var r = agg
  .insert(domain1.map(f1)) // or, looping calls to _add
  .insert(domain2.map(f2)) // to avoid array creation
  .result()[0];

console.log([r.min, r.max]); // [1, 10]

r = agg
  .remove([f1(domain1[0])])
  .remove([f2(domain2[0])])
  .result();
console.log([r.min, r.max]); // [2, 6]
```

**Comment by jheer** [comment]
I have made the change described above for v1.1.7.

**Comment by arvind** [comment]
Ok, this is an interesting option and prototyped in uwdata/vega@52c501c. In my Aggregator subclass, I standardize the schema of the objects sent to the measures monoids. My concern here is with the object creation cost on every aggregation operation. 

Aggregating over just values works for quantitative scales but ordinal/quantile scales aggregate unique values and may, optionally, specify a sorting. This means that I still need to send the aggregator a tuple with groupby+summary fields, I think?

**Comment by arvind** [comment]
One option that extends this pattern further is to add vargs to the add/mod/rem methods that receive values directly. E.g., first arg could be groupby, subsequent args could be the summary fields in order.

**Comment by jheer** [comment]
Does this solve the problem? Now supported in v1.1.8:
```javascript
// return unique values + counts
dl.groupby({name: 'value', get: dl.identity})
  .count();
  .execute([1,1,1,2,2,3,null]));
```

**Comment by arvind** [comment]
Sorry, I might have been unclear. An ordinal scale might specify
```js
dl.groupby("a")
  .summarize({ "b": ["avg"] })
```
Where `a` and `b` differ across multiple schemas (i.e., the scale's domain is unique `a`'s sorted by `b`).

**Comment by jheer** [comment]
Ah yes, sorting. In that case I would feed the aggregator a standardized schema, as you are already doing. Though you might be able to optimize a bit. For example, if there is no sort, use the raw value groupby. If there is a sort, pick a "standard" schema that matches one of your input data sets (ideally the largest, if drawing from multiple sources) to reduce new object generation. Multi-property scale domains are a rare enough occurrence that a performance hit here for large data may not be worth contorting ourselves or our code...
