### ISSUE TITLE
agg._mod doesn't correctly update min

### ISSUE THREAD

**Issue by arvind** [uwdata/datalib#23]
I'm not sure if this is a bug or a question. Perhaps there's something I'm not calling? But the following test case doesn't currently correctly:

```js
var dl = require('./src/index')
var agg = dl.groupby()
  .stream(true)
  .key("_id")
  .summarize({'value': ['min', 'max'] });

var add = [
  { _id: 1, value: 28 },
  { _id: 2, value: 55 },
  { _id: 3, value: 43 },
  { _id: 4, value: 91 },
  { _id: 5, value: 81 },
  { _id: 6, value: 53 },
  { _id: 7, value: 19 },
  { _id: 8, value: 87 },
  { _id: 9, value: 52 },
  { _id: 10, value: 48 },
  { _id: 11, value: 24 },
  { _id: 12, value: 49 },
  { _id: 13, value: 87 },
  { _id: 14, value: 66 },
  { _id: 15, value: 17 },
  { _id: 16, value: 27 },
  { _id: 17, value: 68 },
  { _id: 18, value: 16 },
  { _id: 19, value: 49 },
  { _id: 20, value: 15 }
];

var mod = [
  { _id: 1, value: 56 },
  { _id: 2, value: 110 },
  { _id: 3, value: 86 },
  { _id: 4, value: 182 },
  { _id: 5, value: 162 },
  { _id: 6, value: 106 },
  { _id: 7, value: 38 },
  { _id: 8, value: 174 },
  { _id: 9, value: 104 },
  { _id: 10, value: 96 },
  { _id: 12, value: 98 },
  { _id: 11, value: 48 },
  { _id: 13, value: 174 },
  { _id: 14, value: 132 },
  { _id: 15, value: 34 },
  { _id: 16, value: 54 },
  { _id: 17, value: 136 },
  { _id: 18, value: 32 },
  { _id: 19, value: 98 },
  { _id: 20, value: 30 },
];

for(var i=0, len=add.length; i<len; ++i) {
  agg._add(add[i]);
}

console.log(agg.result());  // Correct: [ { min_value: 15, max_value: 91 } ]

for(i=0, len=mod.length; i<len; ++i) {
  agg._mod(mod[i], add[i]);
}

console.log(agg.result());  // Incorrect: [ { min_value: 15, max_value: 182 } ] Expected min_value == 30
```

**Comment by jheer** [comment]
The problem is how you're passing values to _mod. The method assumes that you made a true modification (i.e., updated values of an exact tuple instance) and that you are passing the modified tuple as the first argument. The example above passes a previously unseen tuple as the first argument.

If you instead do something like this prior to calling _mod, everything works:
```javascript
var prev = dl.duplicate(add[i]);
dl.extend(add[i], mod[i]);
agg._mod(add[i], prev);
```

Fortunately, the weird switch up in this example is not very representative. As Vega 2 transforms modify the original tuple and write the old values to the prev tuple, the current _mod setup should work as-is.

**Comment by arvind** [comment]
I thought that's why we introduced the `key` -- to allow the aggregator to match across tuple instances and not rely on the exact same tuple?

**Comment by jheer** [comment]
The `key` serves that purposes for collector removes, but that's it. My main motivation for adding a key function is that it enables the fastest scheme for consolidating adds and rems in the collector. Spoofing removes is a "bonus", but ideally Vega should not be spoofing removes in the first place. If we stick to the current mod scheme, we avoid collector updates if the groupby fields are unchanged (and so this should be noticeably faster for large data sets). Also, I should note that _mod is not part of the public API: I included it specifically to optimize Vega use.
