### ISSUE TITLE
dl.duplicate does not preserve prototype properties

### ISSUE THREAD

**Issue by arvind** [uwdata/datalib#26]
```js
var a = {a: 1}, b = Object.create(a);
var c = dl.duplicate(b);
// b.a = 1; c = {}
```
This is due to `dl.duplicate` using `JSON.stringify` which does not resolve prototype properties. One possible fix is to walk them manually: http://stackoverflow.com/questions/8779249/how-to-stringify-inherited-objects-to-json

**Comment by arvind** [comment]
An alternative is to provide a `dl.flatten` that does walk the prototype chain. But, I would argue that this is the expected behaviour of `dl.duplicate`

**Comment by jheer** [comment]
Not clear to me which behavior is preferable in the abstract. Is there a
pressing Vega use case here? The datalib duplicate method is identical to
what we had in Vega.

**Comment by arvind** [comment]
I was using `dl.duplicate` to spoof the previous tuple, but I can just as easily use `Object.create,` so I'm closing this issue.

**Comment by jheer** [comment]
Yes, Object.create or dl.extend are better options.
